# Change these first
owner: matematrix # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Homepage
    url: https://home.mats-bueser.info
  - name: Application Head Server
    url: https://mats-bueser.info
  - name: VPN & PiHole
    url: https://mats-bueser.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mats-bueser.info
  # baseUrl: /status
  logoUrl: https://home.mats-bueser.info/wp-content/uploads/2021/02/cropped-Bueser3-300x78.png
  favicon: https://home.mats-bueser.info/wp-content/uploads/fbrfg/favicon-32x32.png
  name: Status | Mats Büser
  introTitle: "Immer up to date bleiben!"
  introMessage: "Ob Wartungsarbeiten, Störungen oder Updates zu den Systemen - hier sehen Sie alles auf einen Blick."
  
status-website:
  theme: ocean

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
